apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SECRET_USERNAME: dXNlcm5hbWU=
  SECRET_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app-container
    image: app-image:1.0
    volumeMounts:
      - name: secret-volume
        mountPath: "/etc/secret"
        readOnly: true
    env: 
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: SECRET_USERNAME
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: SECRET_PASSWORD
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
