apiVersion: v1
kind: Pod
metadata:
  name: app-livenessProbe
  labels:
    name: app-livenessProbe
spec:
  containers:
  - name: doker
    image: gcr.io/k3s-k8s-418912/doker:v.2.0.0
    securityContext:
      runAsNonRoot: true
    livenessProbe:
      exec:
        command: [ "sleep", "5m" ]
    readinessProbe:
      exec:
        command: [ "sleep", "5m" ]
    volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimID: pvc-claim-123456
        volumeMode: Filesystem
        access: ReadWrite
    - name: data-volume-2
      persistentVolumeClaim:
        claimID: pvc-claim-78910
        volumeMode: Filesystem
        access: ReadOnly
    volumeMounts:
    - name: data-volume
      mountPath: /var/data
      readOnly: false
    - name: data-volume-2
      mountPath: /var/data
      readOnly: true
