apiVersion: v1
kind: Pod
metadata:
  name: multi-container-apps
spec:
  containers:
  - name: frontend
    image: busybox
    command: ["echo Hello"]
    ports:
    - containerPort: 80
      name: http
  - name: backend
    image: busybox
    command: ["echo Bye"]
    ports:
    - containerPort: 8080
      name: http
