apiVersion: v1
kind: Pod
metadata:
  name: app-with-resources
spec:
  containers:
  - name: app-container
    image: gcr.io/k3s-k8s-418912/doker:v.2.0.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.2"
        memory: "128Mi"

