apiVersion: v1
kind: Pod
metadata:
  name: app-with-volume
spec:
  containers:
  - name: app-container
    image: gcr.io/k3s-k8s-418912/doker:v.2.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}

