apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-app
    environment: development
  name: my-app
spec:
  containers:
  - name: my-app
    image: gcr.io/k3s-k8s-418912/docker:v.2.0.0
    readinessProbe:
      exec:
        command:
          - ls
          - /bin/true
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Always

